package es.cbgp.upm.ddxotn.logic;

public class DDxDOURIs {

	public static DDxDOURIs INSTANCE = new DDxDOURIs();
	public String DDXDO_URI;
	public String DDXDO_ACRONYM;
	public String DDXDO_PATIENT_URI;
	public String DDXDO_PATIENT_ACRONYM;
	
	public String SNOMED_URI;
	public String SNOMED_ACRONYM;
	
	public String TEMP_ONTOLOGY_URI;
	public String TEMP_ONTOLOGY_ACRONYM;
	
	public String DDXDO_DIAGNOSIS_RELATION;
	public String DDXDO_HAS_TEST_RELATION;
	public String DDXDO_MANIFEST_SIGN_RELATION;
	public String DDXDO_HAS_INPUT_DATA_RELATION;
	public String DDXDO_HAS_CLINICAL_FINDING_RELATION;
	public String DDXDO_HAS_SIGN_RELATION;
	public String DDXDO_HAS_DIAGNOSTIC_TEST_RELATION;
	
	public String TEMP_ONTOLOGY_METHOD_RELATION;
	public String TEMP_ONTOLOGY_VALUE_RELATION;
	public String TEMP_ONTOLOGY_DURATION_RELATION;
	public String TEMP_ONTOLOGY_INTENSITY_RELATION;
	public String TEMP_ONTOLOGY_HAS_PROBABILITY_RELATION;
	public String TEMP_ONTOLOGY_RULE_GENERATED_BY_RELATION;
	public String TEMP_ONTOLOGY_CONFIRMED_BY_RELATION;
	
	public static DDxDOURIs getInstance() {
		return INSTANCE;
	}
	
	private DDxDOURIs() {
		try {
			DDXDO_URI = ConfigManager.getConfig("DDXDO_URI");
			DDXDO_ACRONYM = ConfigManager.getConfig("DDXDO_ACRONYM");
			DDXDO_PATIENT_URI = ConfigManager.getConfig("DDXDO_PATIENT_URI");
			DDXDO_PATIENT_ACRONYM = ConfigManager.getConfig("DDXDO_PATIENT_ACRONYM");
			
			SNOMED_URI = ConfigManager.getConfig("SNOMED_URI");
			SNOMED_ACRONYM = ConfigManager.getConfig("SNOMED_ACRONYM");
			
			TEMP_ONTOLOGY_URI = ConfigManager.getConfig("TEMP_ONTOLOGY_URI");
			TEMP_ONTOLOGY_ACRONYM = ConfigManager.getConfig("TEMP_ONTOLOGY_ACRONYM");
			
			DDXDO_DIAGNOSIS_RELATION = DDXDO_URI + ConfigManager.getConfig("DDXDO_DIAGNOSIS_RELATION");
			DDXDO_HAS_TEST_RELATION = DDXDO_URI + ConfigManager.getConfig("DDXDO_HAS_TEST_RELATION");
			DDXDO_MANIFEST_SIGN_RELATION = DDXDO_URI + ConfigManager.getConfig("DDXDO_MANIFEST_SIGN_RELATION");
			DDXDO_HAS_INPUT_DATA_RELATION = DDXDO_URI + ConfigManager.getConfig("DDXDO_HAS_INPUT_DATA_RELATION");
			DDXDO_HAS_CLINICAL_FINDING_RELATION = DDXDO_URI + ConfigManager.getConfig("DDXDO_HAS_CLINICAL_FINDING_RELATION");
			DDXDO_HAS_SIGN_RELATION = DDXDO_URI + ConfigManager.getConfig("DDXDO_HAS_SIGN_RELATION");
			DDXDO_HAS_DIAGNOSTIC_TEST_RELATION = DDXDO_URI + ConfigManager.getConfig("DDXDO_HAS_DIAGNOSTIC_TEST_RELATION");
			
			TEMP_ONTOLOGY_METHOD_RELATION = TEMP_ONTOLOGY_URI + ConfigManager.getConfig("TEMP_ONTOLOGY_METHOD_RELATION");
			TEMP_ONTOLOGY_VALUE_RELATION = TEMP_ONTOLOGY_URI + ConfigManager.getConfig("TEMP_ONTOLOGY_VALUE_RELATION");
			TEMP_ONTOLOGY_DURATION_RELATION = TEMP_ONTOLOGY_URI + ConfigManager.getConfig("TEMP_ONTOLOGY_DURATION_RELATION");
			TEMP_ONTOLOGY_INTENSITY_RELATION = TEMP_ONTOLOGY_URI + ConfigManager.getConfig("TEMP_ONTOLOGY_INTENSITY_RELATION");
			TEMP_ONTOLOGY_HAS_PROBABILITY_RELATION = TEMP_ONTOLOGY_URI + ConfigManager.getConfig("TEMP_ONTOLOGY_HAS_PROBABILITY_RELATION");
			TEMP_ONTOLOGY_RULE_GENERATED_BY_RELATION = TEMP_ONTOLOGY_URI + ConfigManager.getConfig("TEMP_ONTOLOGY_RULE_GENERATED_BY_RELATION");
			TEMP_ONTOLOGY_CONFIRMED_BY_RELATION = TEMP_ONTOLOGY_URI + ConfigManager.getConfig("TEMP_ONTOLOGY_CONFIRMED_BY_RELATION");
			
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}
